# **Trabajo 1 -  Módulo 1: Introducción a la ciencia de datos con python - Ejercicios 1, 2 y 3**

## **Ejercicio 1**

Dado un valor $n$, realice las siguientes tareas:

1. **Calcular el factorial**: Obtenga el resultado de multiplicar los números del 1 al $n$ (factorial de $n$). Implemente una función que realice este cálculo.

2. **Matriz comparativa de vectores aleatorios**: 
   - Cree dos vectores $V_1$ y $V_2$ de tamaño $n$ con números aleatorios entre 1 y 10
   - Genere un vector $V_3$ donde:
     - $V_3[i] = 0$ si $V_1[i] < V_2[i]$
     - $V_3[i] = 1$ en caso contrario
   - Concatene los tres vectores ($V_1$, $V_2$, $V_3$) como columnas para obtener una matriz de dimensiones $(n \times 3)$

**Sugerencias:**
- Utilice `NumPy` para generar los vectores aleatorios
- Use `np.random.randint()` para los números aleatorios
- Use `np.concatenate()` para combinar los vectores en una matriz
- Pruebe con $n = 10$ como ejemplo

### 1. Calcular el factorial

In [30]:
def factorial(n):
    """Calculo de factorial"""
    if n < 0:
        raise ValueError("El factorial no está definido para números negativos")
    elif n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(10))

3628800

### 2. Matriz comparativa de vectores aleatorios

In [28]:
import numpy as np
n = 10
V1 = np.array([np.random.randint(1, 11) for _ in range(n)])
V2 = np.array([np.random.randint(1, 11) for _ in range(n)])
print("Vector 1:", V1)
print("Vector 2:", V2)

V3 = np.empty(n, dtype=int)

for i in range(n):
    if V1[i] < V2[i]:
        V3[i] = 0
    else:
        V3[i] = 1
print("Vector 3:", V3)

matriz = np.concatenate([V1[:, None], V2[:, None], V3[:, None]], axis=1)

print("Matriz concatenada: \n", matriz)

Vector 1: [10  8  9  2  4  9  1 10 10 10]
Vector 2: [ 4  7  8  2  1  6  8  5  2 10]
Vector 3: [1 1 1 1 1 1 0 1 1 1]
Matriz concatenada:
 [[10  4  1]
 [ 8  7  1]
 [ 9  8  1]
 [ 2  2  1]
 [ 4  1  1]
 [ 9  6  1]
 [ 1  8  0]
 [10  5  1]
 [10  2  1]
 [10 10  1]]

## **Ejercicio 2**

Dado valores $m$ (número de filas) y $n$ (número de columnas), realice las siguientes tareas:

1. **Crear matriz de ceros**: Genere una matriz $A$ de dimensiones $(m \times n)$ inicializada con ceros.

2. **Llenar matriz con números aleatorios (usando `while`)**: 
   - Utilizando un bucle `while`, reemplace cada columna de la matriz $A$ por vectores de números aleatorios enteros en el rango $[-1, 3]$
   - Recorra columna por columna

3. **Transformar elementos (usando `while`)**: 
   - Utilizando dos bucles `while` anidados, recorra todos los elementos de la matriz
   - Reemplace los elementos **negativos** por $-1$
   - Reemplace los elementos **no negativos** (cero o positivos) por $5$

4. **Repetir transformación (usando `for`)**: 
   - Realice el mismo ejercicio del paso 3, pero esta vez utilizando dos bucles `for` anidados
   - Compare los resultados para verificar que ambos métodos producen la misma matriz

**Sugerencias:**
- Use `np.zeros()` para crear la matriz inicial
- Use `np.random.randint()` para generar números aleatorios
- Recuerde que `while` requiere control manual del índice (incremento)
- Compare las dos matrices finales con `np.array_equal()`
- Pruebe con $m = 4$ y $n = 3$ como ejemplo

### 1. Crear matriz de ceros

In [31]:
m = 4
n = 3

A = np.zeros((m, n), dtype=int)

print("Matriz A inicializada: \n", A)

Matriz A inicializada:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

### 2. Llenar matriz con números aleatorios (usando `while`)

In [32]:
i = 0
while i < n:
    vector = np.random.randint(-1, 4, size=m)
    print(f"Vector generado para la columna {i+1}: {vector}")
    A[:, i] = vector
    i += 1

print("Matriz A: \n", A)

Vector generado para la columna 1: [ 3 -1  0  0]
Vector generado para la columna 2: [1 1 2 0]
Vector generado para la columna 3: [ 3  2  0 -1]
Matriz A:
 [[ 3  1  3]
 [-1  1  2]
 [ 0  2  0]
 [ 0  0 -1]]

### 3. Transformar elementos (usando `while`)

In [33]:
i = 0
while i < m:
    j = 0
    while j < n:
        if A[i, j] < 0:
            A[i, j] = -1
        else:
            A[i, j] = 5
        j += 1
    i += 1

print("Matriz A modificada: \n", A)

Matriz A modificada:
 [[ 5  5  5]
 [-1  5  5]
 [ 5  5  5]
 [ 5  5 -1]]

### 4. Repetir transformación (usando `for`)

In [36]:
B = A.copy()
for i in range(m):
    for j in range(n):
        if B[i, j] < 0:
            B[i, j] = -1
        else:
            B[i, j] = 5

print("Matriz A modificada con bucles for: \n", B)

print("¿La matriz resultante es igual con ambos métodos (`while` y `for`)?", np.array_equal(A, B))

Matriz A modificada con bucles for:
 [[ 5  5  5]
 [-1  5  5]
 [ 5  5  5]
 [ 5  5 -1]]
¿La matriz resultante es igual con ambos métodos (`while` y `for`)? True

## **Ejercicio 3**

Se recolectaron datos de 8 estudiantes universitarios y se resumieron en la siguiente tabla:

<div align="center">

|MASA| ESTATURA| GENERO| ESTRATO |FUMA|
|----|---------|--------|--------|----|
|71 |183| HOMBRE |2| NO|
|45| 168 |HOMBRE| 1 |NO|
|50| 164 |HOMBRE| 1 |NO|
|60| 164 |MUJER |3 |SI|
|61| 167 |HOMBRE| 3| SI|
|84| 182 |HOMBRE| 3| NO|
|55| 168 |MUJER |3 |NO|
|60| 170 |HOMBRE| 3 |SI|

</div>

1. Crear un data frame y llamarlo __df__.
2. Realizar un análisis descriptivo básico de todas las variables.
3. Extraer un subconjunto de datos con los primeros 4 estudiantes y llamarlo __subc1__.
4. Extraer las variables categóricas y guardarlas en un subconjunto llamado __subc2__
5. Extraer las variables numéricas y guardarlas en un subconjunto llamado __subc3__

### 1. Crear un data frame y llamarlo __df__.

In [37]:
import pandas as pd
data={
    "Masa":[71, 45, 50, 60, 61, 84, 55, 60],
    "Estatura":[183, 168, 164, 164, 167, 182, 168, 170],
    "Genero":["HOMBRE","HOMBRE","HOMBRE","MUJER","HOMBRE","HOMBRE","MUJER","HOMBRE"],
    "Estrato":[2,1,1,3,3,3,3,3],
    "Fuma":["NO","NO","NO","SI","SI","NO","NO","SI"],
}

df = pd.DataFrame(data)

df

   Masa  Estatura  Genero  Estrato Fuma
0    71       183  HOMBRE        2   NO
1    45       168  HOMBRE        1   NO
2    50       164  HOMBRE        1   NO
3    60       164   MUJER        3   SI
4    61       167  HOMBRE        3   SI
5    84       182  HOMBRE        3   NO
6    55       168   MUJER        3   NO
7    60       170  HOMBRE        3   SI

### 2. Realizar un análisis descriptivo básico de todas las variables.

In [21]:
df.describe(include='all')

             Masa   Estatura  Genero   Estrato Fuma
count    8.000000    8.00000       8  8.000000    8
unique        NaN        NaN       2       NaN    2
top           NaN        NaN  HOMBRE       NaN   NO
freq          NaN        NaN       6       NaN    5
mean    60.750000  170.75000     NaN  2.375000  NaN
std     12.209481    7.53563     NaN  0.916125  NaN
min     45.000000  164.00000     NaN  1.000000  NaN
25%     53.750000  166.25000     NaN  1.750000  NaN
50%     60.000000  168.00000     NaN  3.000000  NaN
75%     63.500000  173.00000     NaN  3.000000  NaN
max     84.000000  183.00000     NaN  3.000000  NaN

Algunas de las estadísticas descriptivas generales obtenidas a partir del conjunto de datos muestran que la masa corporal presenta un promedio de 60,75 kg, con una desviación estándar de 12,21 kg y valores que oscilan entre 45 y 84 kg, lo que evidencia una variabilidad considerable en el peso de los individuos. Por su parte, la estatura registra un promedio de 170,75 cm, con una desviación estándar de 7,54 cm y valores comprendidos entre 164 y 183 cm. En cuanto al género, se observa un predominio de hombres, con 6 de las 8 observaciones, mientras que las 2 restantes corresponden a mujeres. Respecto al estrato socioeconómico, la categoría más frecuente es el estrato 3, presente en 5 observaciones, mientras que los estratos 1 y 2 presentan una menor frecuencia. Finalmente, en relación con la variable Fuma, 5 personas presentan el valor "NO" y 3 el valor "SI", por lo que en la muestra predominan los individuos que no fuman.

### 3. Extraer un subconjunto de datos con los primeros 4 estudiantes y llamarlo __subc1__

In [22]:
subc1 = df.iloc[:4,:]
print("Subconjunto 1:")
subc1

Subconjunto 1:

   Masa  Estatura  Genero  Estrato Fuma
0    71       183  HOMBRE        2   NO
1    45       168  HOMBRE        1   NO
2    50       164  HOMBRE        1   NO
3    60       164   MUJER        3   SI

### 4. Extraer las variables categóricas y guardarlas en un subconjunto llamado __subc2__

In [23]:
subc2 = df.select_dtypes(include=['object', 'category'])
print("Subconjunto 2:")
subc2

Subconjunto 2:

   Genero Fuma
0  HOMBRE   NO
1  HOMBRE   NO
2  HOMBRE   NO
3   MUJER   SI
4  HOMBRE   SI
5  HOMBRE   NO
6   MUJER   NO
7  HOMBRE   SI

### 5. Extraer las variables numéricas y guardarlas en un subconjunto llamado __subc3__

In [24]:
subc3 = df.select_dtypes(include='number')
print("Subconjunto 3:")
subc3

Subconjunto 3:

   Masa  Estatura  Estrato
0    71       183        2
1    45       168        1
2    50       164        1
3    60       164        3
4    61       167        3
5    84       182        3
6    55       168        3
7    60       170        3